
const header = document.getElementById('head');

function helloPerson() {
  var nextItem = [];
  nextItem[0] = prompt("Enter your Name.");
  nextItem[1] = prompt("How are you feeling? Enter your feelings seperated by commas Ex: happy, sad, etc.");


  for (var i = 0; i < nextItem.length; i++) {
    nextItem[i];
  }

  var madLib = " Hello " + nextItem[0] + ", you are feeling " + nextItem[1] + ". ";
  header.innerHTML += "<br>" + madLib;

  //document.write(madLib);
  console.log(madLib);
}



function getRandomImage() {
//declare an array to store the images
var randomImage = new Array();

//insert the URL of images in array
randomImage[0] = "img/Death.png";
randomImage[1] = "img/HangedMan.png";
randomImage[2] = "img/HighPriestess.png";
randomImage[3] = "img/Justice.png";
randomImage[4] = "img/Magician.png";
randomImage[6] = "img/Strength.png";
randomImage[7] = "img/Sun.png";
randomImage[8] = "img/TheEmperor.png";
randomImage[9] = "img/TheFool.png";
randomImage[10] = "img/TheHeirophant.png";
randomImage[11] = "img/TheHermit.png";
randomImage[11] = "img/TheLovers.png";
randomImage[12] = "img/TheMoon.png";
randomImage[13] = "img/Wheel.png";

//loop to display five randomly chosen images at once
for (let i=0; i< 3; i++) {
//generate a number and provide to the image to generate randomly
var number = Math.floor(Math.random()*randomImage.length);
//print the images generated by a random number
document.getElementById("result").innerHTML += '<img src="'+ randomImage[number] +'" style="width:150px" />';
}
}
helloPerson();
